spring.application.name=backend

minio.url=http://minio:9000
minio.accessKey=minioadmin
minio.secretKey=minioadmin
minio.bucketName=product-images


# Database Configuration
spring.datasource.url=jdbc:mysql://mysql:3306/shopping_db?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Schema Generation Settings
spring.jpa.properties.hibernate.hbm2ddl.schema-generation.scripts.action=create
spring.jpa.properties.hibernate.hbm2ddl.schema-generation.scripts.create-target=init.sql

# Enable SQL Logging for Debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# Redis server configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=  # Leave empty if no password is set
spring.data.redis.database=0

## Optional: Connection pool settings (for better performance)
#spring.redis.lettuce.pool.max-active=10
#spring.redis.lettuce.pool.max-idle=5
#spring.redis.lettuce.pool.min-idle=2
#spring.redis.lettuce.pool.max-wait=1000ms

app.jwtSecret=45D81EC1EF61DF9AD8D3E5BB397F9
app.jwtExpirationMs=60000
