package com.ecommerce.backend.mapper;

import com.ecommerce.backend.dto.account.AccountDto;
import com.ecommerce.backend.entity.account.Account;
import com.ecommerce.backend.entity.account.Role;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Named;

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

@Mapper(componentModel = "spring", uses = {AddressMapper.class, CartMapper.class, RoleMapper.class})
public interface AccountMapper {

    // Mapping from AccountDto to Account entity
//    @Mappings({
//            // For example, if the ID is read-only in the DTO and generated by the persistence layer,
//            // you may choose to ignore it when mapping to the entity.
////            @Mapping(target = "id", ignore = true),
////            @Mapping(target = "password", ignore = true)
//    })
    @Mapping(target = "roles", source = "roles", qualifiedByName = "mapUUIDsToRoles")
    Account toEntity(AccountDto accountDto);

    // Mapping from Account entity to AccountDto (response)
    @Mapping(target = "roles", source = "roles", qualifiedByName = "mapRolesToUUIDs")
    AccountDto toDto(Account account);


    @Named("mapRolesToUUIDs")
    default Set<UUID> mapRolesToUUIDs(Set<Role> roles) {
        return roles != null
                ? roles.stream().map(Role::getId).collect(Collectors.toSet())
                : new HashSet<>();
    }

    @Named("mapUUIDsToRoles")
    default Set<Role> mapUUIDsToRoles(Set<UUID> roleIds) {
        return roleIds != null
                ? roleIds.stream()
                .map(id -> {
                    Role role = new Role();
                    role.setId(id);
                    return role;
                })
                .collect(Collectors.toSet())
                : new HashSet<>();
    }
}

