package com.ecommerce.backend.mapper;

import com.ecommerce.backend.dto.account.AccountDto;
import com.ecommerce.backend.entity.account.Account;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Mappings;

@Mapper(componentModel = "spring", uses = {AddressMapper.class, CartMapper.class, RoleMapper.class})
public interface AccountMapper {

    // Mapping from AccountDto to Account entity
    @Mappings({
            // For example, if the ID is read-only in the DTO and generated by the persistence layer,
            // you may choose to ignore it when mapping to the entity.
//            @Mapping(target = "id", ignore = true),
//            @Mapping(target = "password", ignore = true)
    })
    Account toEntity(AccountDto accountDto);

    // Mapping from Account entity to AccountDto (response)
    AccountDto toDto(Account account);
}

